"""Type stubs for riemannopt."""

from typing import Optional
import numpy as np
from numpy.typing import NDArray

# ── Manifold ──────────────────────────────────────────────────────────

class Manifold:
    def dimension(self) -> int: ...
    def name(self) -> str: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

def sphere(n: int) -> Manifold: ...
def euclidean(n: int) -> Manifold: ...
def stiefel(n: int, p: int) -> Manifold: ...
def grassmann(n: int, p: int) -> Manifold: ...
def spd(n: int) -> Manifold: ...
def hyperbolic(n: int) -> Manifold: ...
def oblique(n: int, p: int) -> Manifold: ...

# ── Solvers ───────────────────────────────────────────────────────────

class Solver: ...

def SGD(
    learning_rate: float = 0.01,
    momentum: float = 0.0,
    nesterov: bool = False,
    gradient_clip: Optional[float] = None,
) -> Solver: ...

def Adam(
    learning_rate: float = 0.001,
    beta1: float = 0.9,
    beta2: float = 0.999,
    epsilon: float = 1e-8,
) -> Solver: ...

def LBFGS(memory: int = 10) -> Solver: ...
def CG() -> Solver: ...
def TrustRegion() -> Solver: ...

# ── AutoDiff ──────────────────────────────────────────────────────────

class ScalarVar:
    def __repr__(self) -> str: ...

class VectorVar:
    def __repr__(self) -> str: ...

class MatrixVar:
    def __repr__(self) -> str: ...

class AdSession:
    def __init__(self) -> None: ...
    # Inputs
    def input_vector(self, n: int) -> VectorVar: ...
    def input_matrix(self, rows: int, cols: int) -> MatrixVar: ...
    # Constants
    def constant_scalar(self, val: float) -> ScalarVar: ...
    def constant_vector(self, data: NDArray[np.float64]) -> VectorVar: ...
    def constant_matrix(self, data: NDArray[np.float64]) -> MatrixVar: ...
    # Scalar ops
    def add_s(self, a: ScalarVar, b: ScalarVar) -> ScalarVar: ...
    def sub_s(self, a: ScalarVar, b: ScalarVar) -> ScalarVar: ...
    def mul_s(self, a: ScalarVar, b: ScalarVar) -> ScalarVar: ...
    def div_s(self, a: ScalarVar, b: ScalarVar) -> ScalarVar: ...
    def neg_s(self, a: ScalarVar) -> ScalarVar: ...
    def exp_s(self, a: ScalarVar) -> ScalarVar: ...
    def log_s(self, a: ScalarVar) -> ScalarVar: ...
    def sqrt_s(self, a: ScalarVar) -> ScalarVar: ...
    def sin_s(self, a: ScalarVar) -> ScalarVar: ...
    def cos_s(self, a: ScalarVar) -> ScalarVar: ...
    def abs_s(self, a: ScalarVar) -> ScalarVar: ...
    def pow_s(self, a: ScalarVar, b: ScalarVar) -> ScalarVar: ...
    # Vector ops
    def add_v(self, a: VectorVar, b: VectorVar) -> VectorVar: ...
    def sub_v(self, a: VectorVar, b: VectorVar) -> VectorVar: ...
    def neg_v(self, a: VectorVar) -> VectorVar: ...
    def component_mul_v(self, a: VectorVar, b: VectorVar) -> VectorVar: ...
    def scale_v(self, s: ScalarVar, v: VectorVar) -> VectorVar: ...
    def dot(self, a: VectorVar, b: VectorVar) -> ScalarVar: ...
    def norm_v(self, v: VectorVar) -> ScalarVar: ...
    def norm_sq_v(self, v: VectorVar) -> ScalarVar: ...
    def sum_v(self, v: VectorVar) -> ScalarVar: ...
    # Matrix ops
    def add_m(self, a: MatrixVar, b: MatrixVar) -> MatrixVar: ...
    def sub_m(self, a: MatrixVar, b: MatrixVar) -> MatrixVar: ...
    def neg_m(self, a: MatrixVar) -> MatrixVar: ...
    def scale_m(self, s: ScalarVar, m: MatrixVar) -> MatrixVar: ...
    def mat_mul(self, a: MatrixVar, b: MatrixVar) -> MatrixVar: ...
    def mat_vec(self, m: MatrixVar, v: VectorVar) -> VectorVar: ...
    def transpose_m(self, a: MatrixVar) -> MatrixVar: ...
    def trace_m(self, m: MatrixVar) -> ScalarVar: ...
    def frob_dot(self, a: MatrixVar, b: MatrixVar) -> ScalarVar: ...
    # Fused ops
    def linear_layer(self, a: MatrixVar, x: VectorVar, b: VectorVar) -> VectorVar: ...
    def quad_form(self, x: VectorVar, a: MatrixVar) -> ScalarVar: ...
    # Build problem
    def build_vector_problem(self, loss: ScalarVar) -> "Problem": ...
    def build_matrix_problem(self, loss: ScalarVar) -> "Problem": ...

# ── Problem ───────────────────────────────────────────────────────────

class Problem:
    def __repr__(self) -> str: ...

def rayleigh_quotient(a: NDArray[np.float64]) -> Problem: ...
def quadratic_cost(a: NDArray[np.float64], b: NDArray[np.float64], c: float) -> Problem: ...

# ── Result + Stopping ─────────────────────────────────────────────────

class StoppingCriterion:
    def __init__(
        self,
        max_iterations: int = 1000,
        gradient_tolerance: float = 1e-6,
        function_tolerance: Optional[float] = None,
        max_time_secs: Optional[float] = None,
        target_value: Optional[float] = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class SolverResult:
    value: float
    gradient_norm: Optional[float]
    iterations: int
    function_evaluations: int
    gradient_evaluations: int
    converged: bool
    duration_secs: float
    termination_reason: str
    @property
    def point(self) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

# ── Top-level ─────────────────────────────────────────────────────────

def solve(
    solver: Solver,
    problem: Problem,
    manifold: Manifold,
    initial_point: NDArray[np.float64],
    stopping: Optional[StoppingCriterion] = None,
) -> SolverResult: ...
