"""Type stubs for the ``riemannopt._riemannopt`` native extension module.

This module is compiled from Rust via PyO3 and provides the core
Riemannian optimization primitives.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional, Tuple, Union

import numpy as np
from numpy.typing import ArrayLike, NDArray

# ---------------------------------------------------------------------------
# Version
# ---------------------------------------------------------------------------

__version__: str

# ---------------------------------------------------------------------------
# Sub-modules (populated at import time by PyO3)
# ---------------------------------------------------------------------------

manifolds: _ManifoldModule
optimizers: _OptimizerModule

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class RiemannOptError(Exception): ...
class ManifoldValidationError(RiemannOptError): ...
class OptimizationFailedError(RiemannOptError): ...
class ConvergenceError(OptimizationFailedError): ...
class LineSearchError(OptimizationFailedError): ...
class DimensionMismatchError(RiemannOptError): ...
class NumericalError(RiemannOptError): ...
class NotImplementedMethodError(RiemannOptError): ...

# ---------------------------------------------------------------------------
# Cost function
# ---------------------------------------------------------------------------

class CostFunction:
    """Wrapper around a Python cost function for use by Rust optimizers.

    Prefer :func:`create_cost_function` to construct instances.
    """

    def __init__(
        self,
        cost_fn: Callable[[NDArray[np.float64]], float],
        grad_fn: Optional[Callable[[NDArray[np.float64]], NDArray[np.float64]]] = ...,
        cost_and_grad_fn: Optional[
            Callable[[NDArray[np.float64]], Tuple[float, NDArray[np.float64]]]
        ] = ...,
        dimension: Optional[Union[int, Tuple[int, int]]] = ...,
    ) -> None: ...
    def cost(self, point: ArrayLike) -> float:
        """Evaluate the cost at *point*."""
        ...
    def gradient(self, point: ArrayLike) -> NDArray[np.float64]:
        """Evaluate the Euclidean gradient at *point*."""
        ...
    def cost_and_gradient(
        self, point: ArrayLike
    ) -> Tuple[float, NDArray[np.float64]]:
        """Return ``(cost, gradient)`` at *point*."""
        ...
    def reset_counts(self) -> None:
        """Reset evaluation counters to zero."""
        ...
    @property
    def eval_counts(self) -> Dict[str, int]:
        """Number of cost / gradient / cost_and_gradient evaluations."""
        ...

def create_cost_function(
    cost: Callable[..., Any],
    gradient: Optional[Callable[..., Any]] = ...,
    cost_and_gradient: Optional[Callable[..., Any]] = ...,
    dimension: Optional[Union[int, Tuple[int, int]]] = ...,
    validate: bool = ...,
    auto_detect: bool = ...,
) -> CostFunction:
    """Factory that wraps a Python callable into a :class:`CostFunction`.

    When *gradient* is omitted and *cost* does not return a ``(cost, grad)``
    tuple, finite differences are used automatically.
    """
    ...

# ---------------------------------------------------------------------------
# Callback system
# ---------------------------------------------------------------------------

class CallbackInfo:
    """Snapshot of optimizer state passed to callbacks."""

    iteration: int
    cost: float
    gradient_norm: Optional[float]
    elapsed_seconds: float
    converged: bool
    step_size: Optional[float]
    line_search_iterations: Optional[int]
    trust_region_radius: Optional[float]
    step_accepted: Optional[bool]
    relative_improvement: Optional[float]
    extra_info: Optional[Any]
    @property
    def point(self) -> Optional[NDArray[np.float64]]: ...
    @property
    def gradient(self) -> Optional[NDArray[np.float64]]: ...
    @property
    def search_direction(self) -> Optional[NDArray[np.float64]]: ...

class OptimizationCallback:
    """Base class for callbacks; subclass in Python."""

    def __init__(self) -> None: ...
    def on_optimization_start(self) -> None: ...
    def on_iteration_end(self, info: CallbackInfo) -> bool:
        """Return ``False`` to request early termination."""
        ...
    def on_optimization_end(self, info: CallbackInfo) -> None: ...

class CallbackManager:
    """Manage a collection of callbacks."""

    def __init__(self, callbacks: Optional[List[Any]] = ...) -> None: ...
    def add_callback(self, callback: Any) -> None: ...
    def remove_callback(self, callback: Any) -> bool: ...
    def clear(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def num_callbacks(self) -> int: ...

# ===================================================================
# Manifolds  (riemannopt._riemannopt.manifolds.*)
# ===================================================================

class _ManifoldModule:
    Sphere: type[Sphere]
    Stiefel: type[Stiefel]
    Grassmann: type[Grassmann]
    SPD: type[SPD]
    Euclidean: type[Euclidean]
    Hyperbolic: type[Hyperbolic]
    Oblique: type[Oblique]
    PSDCone: type[PSDCone]
    ProductManifold: type[ProductManifold]

# -- Vector manifolds (Point = 1-D array) --------------------------------

class Sphere:
    r"""Unit sphere :math:`S^{n-1}` in :math:`\mathbb{R}^n`.

    Parameters
    ----------
    dimension : int
        Ambient dimension *n* (must be >= 2).
    """

    def __init__(self, dimension: int) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    def project(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def project_tangent(self, point: ArrayLike, vector: ArrayLike) -> NDArray[np.float64]: ...
    def exp(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def log(self, point: ArrayLike, other: ArrayLike) -> NDArray[np.float64]: ...
    def retract(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def inner(self, point: ArrayLike, u: ArrayLike, v: ArrayLike) -> float: ...
    def norm(self, point: ArrayLike, tangent: ArrayLike) -> float: ...
    def distance(self, x: ArrayLike, y: ArrayLike) -> float: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def random_tangent(self, point: ArrayLike, scale: float = ...) -> NDArray[np.float64]: ...
    def parallel_transport(self, from_point: ArrayLike, to_point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def contains(self, point: Any, atol: float = ...) -> bool: ...
    def is_tangent(self, point: Any, vector: Any, atol: float = ...) -> bool: ...

class Euclidean:
    r"""Flat Euclidean space :math:`\mathbb{R}^n`."""

    def __init__(self, n: int) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    @property
    def name(self) -> str: ...
    def is_point_on_manifold(self, point: ArrayLike, tol: Optional[float] = ...) -> bool: ...
    def project_point(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def project_tangent(self, point: ArrayLike, vector: ArrayLike) -> NDArray[np.float64]: ...
    def inner(self, point: ArrayLike, u: ArrayLike, v: ArrayLike) -> float: ...
    def norm(self, point: ArrayLike, vector: ArrayLike) -> float: ...
    def retract(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def inverse_retract(self, point: ArrayLike, other: ArrayLike) -> NDArray[np.float64]: ...
    def euclidean_to_riemannian_gradient(self, point: ArrayLike, euclidean_grad: ArrayLike) -> NDArray[np.float64]: ...
    def parallel_transport(self, from_point: ArrayLike, to_point: ArrayLike, vector: ArrayLike) -> NDArray[np.float64]: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def random_tangent(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def distance(self, x: ArrayLike, y: ArrayLike) -> float: ...
    def is_flat(self) -> bool: ...

class Hyperbolic:
    r"""Hyperbolic space :math:`\mathbb{H}^n` (Poincaré ball model)."""

    def __init__(self, n: int, curvature: float = ...) -> None: ...
    @property
    def n(self) -> int: ...
    @property
    def curvature(self) -> float: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    def project(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def project_tangent(self, point: ArrayLike, vector: ArrayLike) -> NDArray[np.float64]: ...
    def exp(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def log(self, point: ArrayLike, other: ArrayLike) -> NDArray[np.float64]: ...
    def retract(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def minkowski_inner(self, x: ArrayLike, y: ArrayLike) -> float: ...
    def inner(self, point: ArrayLike, u: ArrayLike, v: ArrayLike) -> float: ...
    def norm(self, point: ArrayLike, tangent: ArrayLike) -> float: ...
    def distance(self, x: ArrayLike, y: ArrayLike) -> float: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def random_tangent(self, point: ArrayLike, scale: float = ...) -> NDArray[np.float64]: ...
    def parallel_transport(self, from_point: ArrayLike, to_point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def contains(self, point: Any, atol: float = ...) -> bool: ...
    def is_tangent(self, point: Any, vector: Any, atol: float = ...) -> bool: ...

# -- Matrix manifolds (Point = 2-D array) --------------------------------

class Stiefel:
    r"""Stiefel manifold :math:`\mathrm{St}(n, p)` of orthonormal frames."""

    def __init__(self, n: int, p: int) -> None: ...
    @property
    def n(self) -> int: ...
    @property
    def p(self) -> int: ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    def project(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def project_tangent(self, point: ArrayLike, vector: ArrayLike) -> NDArray[np.float64]: ...
    def exp(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def log(self, point: ArrayLike, other: ArrayLike) -> NDArray[np.float64]: ...
    def retract(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def inner(self, point: ArrayLike, u: ArrayLike, v: ArrayLike) -> float: ...
    def norm(self, point: ArrayLike, tangent: ArrayLike) -> float: ...
    def distance(self, x: ArrayLike, y: ArrayLike) -> float: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def random_tangent(self, point: ArrayLike, scale: float = ...) -> NDArray[np.float64]: ...
    def parallel_transport(self, from_point: ArrayLike, to_point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def contains(self, point: Any, atol: float = ...) -> bool: ...
    def is_tangent(self, point: Any, vector: Any, atol: float = ...) -> bool: ...

class Grassmann:
    r"""Grassmann manifold :math:`\mathrm{Gr}(n, p)` of *p*-dimensional subspaces."""

    def __init__(self, n: int, p: int) -> None: ...
    @property
    def n(self) -> int: ...
    @property
    def p(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    def project(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def project_tangent(self, point: ArrayLike, vector: ArrayLike) -> NDArray[np.float64]: ...
    def exp(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def log(self, point: ArrayLike, other: ArrayLike) -> NDArray[np.float64]: ...
    def retract(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def inner(self, point: ArrayLike, u: ArrayLike, v: ArrayLike) -> float: ...
    def norm(self, point: ArrayLike, tangent: ArrayLike) -> float: ...
    def distance(self, x: ArrayLike, y: ArrayLike) -> float: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def random_tangent(self, point: ArrayLike, scale: float = ...) -> NDArray[np.float64]: ...
    def parallel_transport(self, from_point: ArrayLike, to_point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def contains(self, point: Any, atol: float = ...) -> bool: ...
    def is_tangent(self, point: Any, vector: Any, atol: float = ...) -> bool: ...

class SPD:
    r"""Symmetric positive-definite matrices :math:`\mathcal{S}_{++}^n`."""

    def __init__(self, n: int) -> None: ...
    @property
    def n(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    def project(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def project_tangent(self, point: ArrayLike, vector: ArrayLike) -> NDArray[np.float64]: ...
    def exp(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def log(self, point: ArrayLike, other: ArrayLike) -> NDArray[np.float64]: ...
    def retract(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def inner(self, point: ArrayLike, u: ArrayLike, v: ArrayLike) -> float: ...
    def norm(self, point: ArrayLike, tangent: ArrayLike) -> float: ...
    def distance(self, x: ArrayLike, y: ArrayLike) -> float: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def random_tangent(self, point: ArrayLike, scale: float = ...) -> NDArray[np.float64]: ...
    def parallel_transport(self, from_point: ArrayLike, to_point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def contains(self, point: Any, atol: float = ...) -> bool: ...
    def is_tangent(self, point: Any, vector: Any, atol: float = ...) -> bool: ...

class Oblique:
    r"""Oblique manifold :math:`\mathrm{OB}(n, p)` — matrices with unit-norm columns."""

    def __init__(self, n: int, p: int) -> None: ...
    @property
    def n(self) -> int: ...
    @property
    def p(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    def contains(self, point: ArrayLike, atol: float = ...) -> bool: ...
    def project(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def project_tangent(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def exp(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def log(self, x: ArrayLike, y: ArrayLike) -> NDArray[np.float64]: ...
    def retract(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def inverse_retract(self, x: ArrayLike, y: ArrayLike) -> NDArray[np.float64]: ...
    def inner(self, point: ArrayLike, u: ArrayLike, v: ArrayLike) -> float: ...
    def norm(self, point: ArrayLike, tangent: ArrayLike) -> float: ...
    def distance(self, x: ArrayLike, y: ArrayLike) -> float: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def random_tangent(self, point: ArrayLike, scale: float = ...) -> NDArray[np.float64]: ...
    def parallel_transport(self, from_point: ArrayLike, to_point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...

class PSDCone:
    r"""Positive semi-definite cone :math:`\mathcal{S}_+^n`."""

    def __init__(self, n: int) -> None: ...
    @property
    def n(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    def contains(self, point: ArrayLike, atol: float = ...) -> bool: ...
    def project(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def project_tangent(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def retract(self, point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...
    def inverse_retract(self, x: ArrayLike, y: ArrayLike) -> NDArray[np.float64]: ...
    def inner(self, point: ArrayLike, u: ArrayLike, v: ArrayLike) -> float: ...
    def norm(self, point: ArrayLike, tangent: ArrayLike) -> float: ...
    def random_point(self) -> NDArray[np.float64]: ...
    def random_tangent(self, point: ArrayLike, scale: float = ...) -> NDArray[np.float64]: ...
    def parallel_transport(self, from_point: ArrayLike, to_point: ArrayLike, tangent: ArrayLike) -> NDArray[np.float64]: ...

class ProductManifold:
    """Cartesian product of manifolds."""

    def __init__(self, manifolds: List[Any]) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    @property
    def n_manifolds(self) -> int: ...
    @property
    def manifolds(self) -> List[Any]: ...
    def random_point(self) -> Any: ...
    def project(self, point: Any) -> Any: ...
    def exp(self, point: Any, tangent: Any) -> Any: ...
    def random_tangent(self, point: Any) -> Any: ...
    def project_tangent(self, point: Any, vector: Any) -> Any: ...
    def retract(self, point: Any, tangent: Any) -> Any: ...
    def inner(self, point: Any, u: Any, v: Any) -> float: ...

# ===================================================================
# Optimizers  (riemannopt._riemannopt.optimizers.*)
# ===================================================================

class _OptimizerModule:
    SGD: type[SGD]
    Adam: type[Adam]
    LBFGS: type[LBFGS]
    ConjugateGradient: type[ConjugateGradient]
    Newton: type[Newton]
    TrustRegion: type[TrustRegion]
    NaturalGradient: type[NaturalGradient]
    OptimizationResult: type[OptimizationResult]
    def optimize(self, cost_function: CostFunction, manifold: Any, initial_point: ArrayLike, optimizer: str = ..., max_iterations: int = ..., gradient_tolerance: float = ...) -> OptimizationResult: ...
    def create_optimizer(self, optimizer_name: str, **kwargs: Any) -> Any: ...

class OptimizationResult:
    """Result returned by all optimizers."""

    @property
    def point(self) -> NDArray[np.float64]: ...
    @property
    def x(self) -> NDArray[np.float64]: ...
    @property
    def value(self) -> float: ...
    @property
    def cost(self) -> float: ...
    @property
    def gradient_norm(self) -> Optional[float]: ...
    @property
    def converged(self) -> bool: ...
    @property
    def success(self) -> bool: ...
    @property
    def iterations(self) -> int: ...
    @property
    def function_evals(self) -> int: ...
    @property
    def gradient_evals(self) -> int: ...
    @property
    def time_seconds(self) -> float: ...
    @property
    def termination_reason(self) -> str: ...
    def summary(self) -> str: ...
    def as_dict(self) -> Dict[str, Any]: ...

class SGD:
    """Riemannian SGD with optional momentum."""
    def __init__(self, learning_rate: float = ..., momentum: float = ...) -> None: ...
    def optimize(self, cost_function: CostFunction, manifold: Any, initial_point: ArrayLike, max_iterations: int, gradient_tolerance: Optional[float] = ..., callback: Optional[Any] = ..., target_value: Optional[float] = ..., max_time: Optional[float] = ...) -> OptimizationResult: ...

class Adam:
    """Riemannian Adam."""
    def __init__(self, learning_rate: float = ..., beta1: float = ..., beta2: float = ..., epsilon: float = ..., amsgrad: bool = ...) -> None: ...
    @property
    def config(self) -> Dict[str, Any]: ...
    def optimize(self, cost_function: CostFunction, manifold: Any, initial_point: ArrayLike, max_iterations: int, gradient_tolerance: Optional[float] = ..., callback: Optional[Any] = ..., target_value: Optional[float] = ..., max_time: Optional[float] = ...) -> OptimizationResult: ...

class LBFGS:
    """Riemannian L-BFGS."""
    def __init__(self, memory_size: int = ..., max_line_search_iterations: int = ..., c1: float = ..., c2: float = ..., initial_step_size: float = ...) -> None: ...
    @property
    def config(self) -> Dict[str, Any]: ...
    def optimize(self, cost_function: CostFunction, manifold: Any, initial_point: ArrayLike, max_iterations: int, gradient_tolerance: Optional[float] = ..., callback: Optional[Any] = ..., target_value: Optional[float] = ..., max_time: Optional[float] = ...) -> OptimizationResult: ...

class ConjugateGradient:
    """Riemannian nonlinear conjugate gradient."""
    def __init__(self, method: str = ..., reset_every: Optional[int] = ..., max_line_search_iterations: int = ..., c1: float = ..., c2: float = ...) -> None: ...
    @property
    def config(self) -> Dict[str, Any]: ...
    def optimize(self, cost_function: CostFunction, manifold: Any, initial_point: ArrayLike, max_iterations: int, gradient_tolerance: Optional[float] = ..., callback: Optional[Any] = ..., target_value: Optional[float] = ..., max_time: Optional[float] = ...) -> OptimizationResult: ...

class Newton:
    """Riemannian Newton method."""
    def __init__(self, max_cg_iterations: Optional[int] = ..., cg_tolerance: float = ..., use_line_search: bool = ..., alpha: float = ..., beta: float = ..., max_line_search_iterations: int = ..., force_positive_definite: bool = ...) -> None: ...
    @property
    def config(self) -> Dict[str, Any]: ...
    def optimize(self, cost_function: CostFunction, manifold: Any, initial_point: ArrayLike, max_iterations: int, gradient_tolerance: Optional[float] = ..., callback: Optional[Any] = ..., target_value: Optional[float] = ..., max_time: Optional[float] = ...) -> OptimizationResult: ...

class TrustRegion:
    """Riemannian trust-region method."""
    def __init__(self, initial_radius: float = ..., max_radius: float = ..., eta: float = ..., radius_decrease_factor: float = ..., radius_increase_factor: float = ..., subproblem_solver: str = ..., max_subproblem_iterations: Optional[int] = ...) -> None: ...
    @property
    def config(self) -> Dict[str, Any]: ...
    def optimize(self, cost_function: CostFunction, manifold: Any, initial_point: ArrayLike, max_iterations: int, gradient_tolerance: Optional[float] = ..., callback: Optional[Any] = ..., target_value: Optional[float] = ..., max_time: Optional[float] = ...) -> OptimizationResult: ...

class NaturalGradient:
    """Riemannian natural gradient descent."""
    def __init__(self, learning_rate: float = ..., fisher_damping: float = ..., fisher_subsample: Optional[int] = ..., momentum: float = ...) -> None: ...
    @property
    def config(self) -> Dict[str, Any]: ...
    def optimize(self, cost_function: CostFunction, manifold: Any, initial_point: ArrayLike, max_iterations: int, gradient_tolerance: Optional[float] = ..., callback: Optional[Any] = ..., target_value: Optional[float] = ..., max_time: Optional[float] = ...) -> OptimizationResult: ...
