"""Type stubs for the RiemannOpt Rust extension module."""

from typing import Any, Optional, Tuple, List, Dict, Union, Callable, Protocol
import numpy as np
import numpy.typing as npt

__version__: str

# Callback types
class CallbackInfo:
    """Information passed to callbacks during optimization."""
    iteration: int
    cost: float
    gradient_norm: Optional[float]
    elapsed_seconds: float
    converged: bool
    step_size: Optional[float]
    line_search_iterations: Optional[int]
    trust_region_radius: Optional[float]
    step_accepted: Optional[bool]
    relative_improvement: Optional[float]
    extra_info: Optional[Any]
    
    @property
    def point(self) -> Optional[npt.NDArray[np.float64]]: ...
    
    @property
    def gradient(self) -> Optional[npt.NDArray[np.float64]]: ...
    
    @property
    def search_direction(self) -> Optional[npt.NDArray[np.float64]]: ...
    
    def __repr__(self) -> str: ...

class OptimizationCallback:
    """Base class for optimization callbacks."""
    def __init__(self) -> None: ...
    def on_optimization_start(self) -> None: ...
    def on_iteration_end(self, info: CallbackInfo) -> bool: ...
    def on_optimization_end(self, info: CallbackInfo) -> None: ...

class CallbackManager:
    """Manager for multiple callbacks."""
    enabled: bool
    
    def __init__(self, callbacks: Optional[List[Any]] = None) -> None: ...
    def add_callback(self, callback: Any) -> None: ...
    def remove_callback(self, callback: Any) -> bool: ...
    def clear(self) -> None: ...
    
    @property
    def num_callbacks(self) -> int: ...
    
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

def create_callback_manager(*callbacks: Any) -> CallbackManager: ...

# Manifolds
class Sphere:
    """Sphere manifold S^{n-1} = {x ∈ ℝ^n : ||x|| = 1}."""
    
    def __init__(self, n: int) -> None: ...
    
    @property
    def n(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    
    def contains(self, point: npt.NDArray[np.float64], atol: float = 1e-10) -> bool: ...
    def project(self, point: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def project_tangent(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def retract(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inverse_retract(self, x: npt.NDArray[np.float64], y: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inner(self, point: npt.NDArray[np.float64], u: npt.NDArray[np.float64], v: npt.NDArray[np.float64]) -> float: ...
    def norm(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> float: ...
    def random_point(self) -> npt.NDArray[np.float64]: ...
    def random_tangent(self, point: npt.NDArray[np.float64], scale: float = 1.0) -> npt.NDArray[np.float64]: ...
    def parallel_transport(self, from_point: npt.NDArray[np.float64], to_point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class Stiefel:
    """Stiefel manifold St(n,p) = {X ∈ ℝ^{n×p} : X^T X = I_p}."""
    
    def __init__(self, n: int, p: int) -> None: ...
    
    @property
    def n(self) -> int: ...
    @property
    def p(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    
    def contains(self, point: npt.NDArray[np.float64], atol: float = 1e-10) -> bool: ...
    def project(self, point: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def project_tangent(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def retract(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inverse_retract(self, x: npt.NDArray[np.float64], y: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inner(self, point: npt.NDArray[np.float64], u: npt.NDArray[np.float64], v: npt.NDArray[np.float64]) -> float: ...
    def norm(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> float: ...
    def random_point(self) -> npt.NDArray[np.float64]: ...
    def random_tangent(self, point: npt.NDArray[np.float64], scale: float = 1.0) -> npt.NDArray[np.float64]: ...
    def parallel_transport(self, from_point: npt.NDArray[np.float64], to_point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class Grassmann:
    """Grassmann manifold Gr(n,p) of p-dimensional subspaces in ℝ^n."""
    
    def __init__(self, n: int, p: int) -> None: ...
    
    @property
    def n(self) -> int: ...
    @property
    def p(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    
    def contains(self, point: npt.NDArray[np.float64], atol: float = 1e-10) -> bool: ...
    def project(self, point: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def project_tangent(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def retract(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inverse_retract(self, x: npt.NDArray[np.float64], y: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inner(self, point: npt.NDArray[np.float64], u: npt.NDArray[np.float64], v: npt.NDArray[np.float64]) -> float: ...
    def norm(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> float: ...
    def random_point(self) -> npt.NDArray[np.float64]: ...
    def random_tangent(self, point: npt.NDArray[np.float64], scale: float = 1.0) -> npt.NDArray[np.float64]: ...
    def parallel_transport(self, from_point: npt.NDArray[np.float64], to_point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class SPD:
    """Symmetric Positive Definite manifold S++^n."""
    
    def __init__(self, n: int) -> None: ...
    
    @property
    def n(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    
    def contains(self, point: npt.NDArray[np.float64], atol: float = 1e-10) -> bool: ...
    def project(self, point: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def project_tangent(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def retract(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inverse_retract(self, x: npt.NDArray[np.float64], y: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inner(self, point: npt.NDArray[np.float64], u: npt.NDArray[np.float64], v: npt.NDArray[np.float64]) -> float: ...
    def norm(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> float: ...
    def random_point(self) -> npt.NDArray[np.float64]: ...
    def random_tangent(self, point: npt.NDArray[np.float64], scale: float = 1.0) -> npt.NDArray[np.float64]: ...
    def parallel_transport(self, from_point: npt.NDArray[np.float64], to_point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class PSDCone:
    """Positive Semi-Definite cone S+^n."""
    
    def __init__(self, n: int) -> None: ...
    
    @property
    def n(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    
    def contains(self, point: npt.NDArray[np.float64], atol: float = 1e-10) -> bool: ...
    def project(self, point: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def project_tangent(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def retract(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inverse_retract(self, x: npt.NDArray[np.float64], y: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inner(self, point: npt.NDArray[np.float64], u: npt.NDArray[np.float64], v: npt.NDArray[np.float64]) -> float: ...
    def norm(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> float: ...
    def random_point(self) -> npt.NDArray[np.float64]: ...
    def random_tangent(self, point: npt.NDArray[np.float64], scale: float = 1.0) -> npt.NDArray[np.float64]: ...
    def parallel_transport(self, from_point: npt.NDArray[np.float64], to_point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class Hyperbolic:
    """Hyperbolic manifold H^n in the hyperboloid model."""
    
    def __init__(self, n: int) -> None: ...
    
    @property
    def n(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    
    def contains(self, point: npt.NDArray[np.float64], atol: float = 1e-10) -> bool: ...
    def project(self, point: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def project_tangent(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def retract(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inverse_retract(self, x: npt.NDArray[np.float64], y: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inner(self, point: npt.NDArray[np.float64], u: npt.NDArray[np.float64], v: npt.NDArray[np.float64]) -> float: ...
    def norm(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> float: ...
    def random_point(self) -> npt.NDArray[np.float64]: ...
    def random_tangent(self, point: npt.NDArray[np.float64], scale: float = 1.0) -> npt.NDArray[np.float64]: ...
    def parallel_transport(self, from_point: npt.NDArray[np.float64], to_point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class Euclidean:
    """Euclidean manifold ℝ^n."""
    
    def __init__(self, n: int) -> None: ...
    
    @property
    def n(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    
    def is_point_on_manifold(self, point: npt.NDArray[np.float64], tol: Optional[float] = None) -> bool: ...
    def project_point(self, point: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def project_tangent(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def retract(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inverse_retract(self, x: npt.NDArray[np.float64], y: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def inner(self, point: npt.NDArray[np.float64], u: npt.NDArray[np.float64], v: npt.NDArray[np.float64]) -> float: ...
    def norm(self, point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> float: ...
    def random_point(self) -> npt.NDArray[np.float64]: ...
    def random_tangent(self, point: npt.NDArray[np.float64], scale: float = 1.0) -> npt.NDArray[np.float64]: ...
    def parallel_transport(self, from_point: npt.NDArray[np.float64], to_point: npt.NDArray[np.float64], tangent: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class ProductManifold:
    """Product of multiple manifolds."""
    
    def __init__(self, *manifolds: Any) -> None: ...
    
    @property
    def manifolds(self) -> List[Any]: ...
    @property
    def dim(self) -> int: ...
    @property
    def ambient_dim(self) -> int: ...
    
    def contains(self, point: Tuple[npt.NDArray[np.float64], ...], atol: float = 1e-10) -> bool: ...
    def project(self, point: Tuple[npt.NDArray[np.float64], ...]) -> Tuple[npt.NDArray[np.float64], ...]: ...
    def project_tangent(self, point: Tuple[npt.NDArray[np.float64], ...], tangent: Tuple[npt.NDArray[np.float64], ...]) -> Tuple[npt.NDArray[np.float64], ...]: ...
    def retract(self, point: Tuple[npt.NDArray[np.float64], ...], tangent: Tuple[npt.NDArray[np.float64], ...]) -> Tuple[npt.NDArray[np.float64], ...]: ...
    def inverse_retract(self, x: Tuple[npt.NDArray[np.float64], ...], y: Tuple[npt.NDArray[np.float64], ...]) -> Tuple[npt.NDArray[np.float64], ...]: ...
    def inner(self, point: Tuple[npt.NDArray[np.float64], ...], u: Tuple[npt.NDArray[np.float64], ...], v: Tuple[npt.NDArray[np.float64], ...]) -> float: ...
    def norm(self, point: Tuple[npt.NDArray[np.float64], ...], tangent: Tuple[npt.NDArray[np.float64], ...]) -> float: ...
    def random_point(self) -> Tuple[npt.NDArray[np.float64], ...]: ...
    def random_tangent(self, point: Tuple[npt.NDArray[np.float64], ...], scale: float = 1.0) -> Tuple[npt.NDArray[np.float64], ...]: ...
    def parallel_transport(self, from_point: Tuple[npt.NDArray[np.float64], ...], to_point: Tuple[npt.NDArray[np.float64], ...], tangent: Tuple[npt.NDArray[np.float64], ...]) -> Tuple[npt.NDArray[np.float64], ...]: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

# Cost functions
class CostFunction:
    """Base cost function."""
    def cost(self, point: npt.NDArray[np.float64]) -> float: ...
    def gradient(self, point: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
    def cost_and_gradient(self, point: npt.NDArray[np.float64]) -> Tuple[float, npt.NDArray[np.float64]]: ...

# Optimizers
class Adam:
    """Adam optimizer."""
    
    def __init__(
        self,
        learning_rate: float = 0.001,
        beta1: float = 0.9,
        beta2: float = 0.999,
        epsilon: float = 1e-8,
        amsgrad: bool = False
    ) -> None: ...
    
    def optimize(
        self,
        manifold: Any,
        cost_fn: Union[CostFunction, Callable],
        initial_point: npt.NDArray[np.float64],
        max_iterations: int = 100,
        gradient_tolerance: float = 1e-6,
        cost_tolerance: float = 1e-8,
        callback: Optional[Union[OptimizationCallback, CallbackManager, Callable]] = None
    ) -> Dict[str, Any]: ...
    
    def __repr__(self) -> str: ...

class SGD:
    """Stochastic Gradient Descent optimizer."""
    
    def __init__(
        self,
        learning_rate: float = 0.01,
        momentum: float = 0.0,
        nesterov: bool = False,
        decay_rate: float = 0.0
    ) -> None: ...
    
    def optimize(
        self,
        manifold: Any,
        cost_fn: Union[CostFunction, Callable],
        initial_point: npt.NDArray[np.float64],
        max_iterations: int = 100,
        gradient_tolerance: float = 1e-6,
        cost_tolerance: float = 1e-8,
        callback: Optional[Union[OptimizationCallback, CallbackManager, Callable]] = None
    ) -> Dict[str, Any]: ...
    
    def __repr__(self) -> str: ...

class LBFGS:
    """Limited-memory BFGS optimizer."""
    
    def __init__(
        self,
        memory_size: int = 10,
        line_search_max_iterations: int = 20,
        line_search_c1: float = 1e-4,
        line_search_c2: float = 0.9
    ) -> None: ...
    
    def optimize(
        self,
        manifold: Any,
        cost_fn: Union[CostFunction, Callable],
        initial_point: npt.NDArray[np.float64],
        max_iterations: int = 100,
        gradient_tolerance: float = 1e-6,
        cost_tolerance: float = 1e-8,
        callback: Optional[Union[OptimizationCallback, CallbackManager, Callable]] = None
    ) -> Dict[str, Any]: ...
    
    def __repr__(self) -> str: ...

class ConjugateGradient:
    """Conjugate Gradient optimizer."""
    
    def __init__(
        self,
        variant: str = "FletcherReeves",
        line_search_max_iterations: int = 20,
        line_search_c1: float = 1e-4,
        line_search_c2: float = 0.1
    ) -> None: ...
    
    def optimize(
        self,
        manifold: Any,
        cost_fn: Union[CostFunction, Callable],
        initial_point: npt.NDArray[np.float64],
        max_iterations: int = 100,
        gradient_tolerance: float = 1e-6,
        cost_tolerance: float = 1e-8,
        callback: Optional[Union[OptimizationCallback, CallbackManager, Callable]] = None
    ) -> Dict[str, Any]: ...
    
    def __repr__(self) -> str: ...

class TrustRegion:
    """Trust Region optimizer."""
    
    def __init__(
        self,
        initial_radius: float = 1.0,
        max_radius: float = 10.0,
        eta: float = 0.1,
        rho_threshold: float = 0.25,
        subproblem_max_iterations: int = 100
    ) -> None: ...
    
    def optimize(
        self,
        manifold: Any,
        cost_fn: Union[CostFunction, Callable],
        initial_point: npt.NDArray[np.float64],
        max_iterations: int = 100,
        gradient_tolerance: float = 1e-6,
        cost_tolerance: float = 1e-8,
        callback: Optional[Union[OptimizationCallback, CallbackManager, Callable]] = None
    ) -> Dict[str, Any]: ...
    
    def __repr__(self) -> str: ...

class Newton:
    """Newton's method optimizer."""
    
    def __init__(
        self,
        line_search: bool = True,
        line_search_max_iterations: int = 20,
        line_search_c1: float = 1e-4,
        regularization: float = 1e-8
    ) -> None: ...
    
    def optimize(
        self,
        manifold: Any,
        cost_fn: Union[CostFunction, Callable],
        initial_point: npt.NDArray[np.float64],
        max_iterations: int = 100,
        gradient_tolerance: float = 1e-6,
        cost_tolerance: float = 1e-8,
        callback: Optional[Union[OptimizationCallback, CallbackManager, Callable]] = None
    ) -> Dict[str, Any]: ...
    
    def __repr__(self) -> str: ...

class NaturalGradient:
    """Natural Gradient optimizer."""
    
    def __init__(
        self,
        learning_rate: float = 0.01,
        regularization: float = 1e-8,
        momentum: float = 0.0
    ) -> None: ...
    
    def optimize(
        self,
        manifold: Any,
        cost_fn: Union[CostFunction, Callable],
        initial_point: npt.NDArray[np.float64],
        max_iterations: int = 100,
        gradient_tolerance: float = 1e-6,
        cost_tolerance: float = 1e-8,
        callback: Optional[Union[OptimizationCallback, CallbackManager, Callable]] = None
    ) -> Dict[str, Any]: ...
    
    def __repr__(self) -> str: ...

# Factory functions
def create_optimizer(name: str, **kwargs: Any) -> Any:
    """Create an optimizer by name."""
    ...

# Exceptions
class RiemannOptError(Exception):
    """Base exception for RiemannOpt errors."""
    ...

class ManifoldValidationError(RiemannOptError):
    """Error in manifold validation."""
    ...

class OptimizationFailedError(RiemannOptError):
    """Optimization algorithm failed."""
    ...

class ConvergenceError(OptimizationFailedError):
    """Algorithm failed to converge."""
    ...

class LineSearchError(OptimizationFailedError):
    """Line search failed."""
    ...

class DimensionMismatchError(RiemannOptError):
    """Dimension mismatch in operations."""
    ...

class NumericalError(RiemannOptError):
    """Numerical computation error."""
    ...

class NotImplementedMethodError(RiemannOptError):
    """Method not implemented."""
    ...